[build]
  functions = "functions_build"
  command   = "npm run build"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"